### ISSUE TITLE
Misplaced elements

### ISSUE THREAD

**Issue by michael-maltsev** [ShizukuIchi/pdf-editor#12]
A very nice project, well done! One problem that I saw is that for some PDF files, the added elements are mis-placed. It looks as if they're rotated by 90 degrees.

Here's an example for such a file:
[example-vertical-bug.pdf](https://github.com/ShizukuIchi/pdf-editor/files/5470411/example-vertical-bug.pdf)

Here's a short recording demonstrating the bug:
![VSwlLOKyiu](https://user-images.githubusercontent.com/36999014/97798439-b8d56c00-1c2e-11eb-8f0c-06e1961e3098.gif)

**Comment by ShizukuIchi** [comment]
Thank you very much. Bug fixed (#14). 😀

**Comment by michael-maltsev** [comment]
Thanks. Looks like it's fixed now, except that the pdf is displayed as rotated while editing:

![image](https://user-images.githubusercontent.com/36999014/98024552-23de9880-1e11-11eb-87da-3e1885fb3872.png)
