### ISSUE TITLE
Does not work on PDFs with multiple pages

### ISSUE THREAD

**Issue by ForGorNorPor** [ShizukuIchi/pdf-editor#39]
I had two issues when trying to use this tool on a multi page document:
1. Inserting a new element always appears on top, no matter on which page I currently look at
2. Dragging an element out of the limits of the first page is not possible as it gets cropped an becomes invisible.

I tested this on Firefox 100.0

Besides that, thanks a lot for this great tool!

**Comment by casrou** [comment]
Click on another page and new elements will be inserted on that instead.

**Comment by ForGorNorPor** [comment]
Oh, wow. I cannot believe I missed that. Thanks, that does work as expected
