### ISSUE TITLE
Not working on nodejs server

### ISSUE THREAD

**Issue by rahimnagori** [ShizukuIchi/pdf-editor#6]
I have setup this dependency on a VPS server.
Run the following commands : 

> git clone

inside pdf-editor
```

> npm install
> npm run build
> npm run start

```
After npm start, this is the response : 

>  Your application is ready~! 🚀
> 
>   - Local:      http://localhost:5000
> 
> ────────────────── LOGS ──────────────────

My first question is why there is localhost in place of domain name?
Second this is not working, why?

---------------- Update
I've been trying to change the host from 'localhost' to 'myDomain' from the following file:
https://github.com/ShizukuIchi/pdf-editor/blob/f3aea5c9799650def6a03fdc588e6261537f988b/rollup.config.js#L57

But seems like changing here doesn't effect anything.
Any help?

**Comment by titulebolide** [comment]
It is sometimes not that bad to have it opening as a local server, then setting up a reverse-proxy using apache or nginx.
By doing so you will be able to easily setting up https over this website

**Comment by borhanreo** [comment]
**I have same. I want to run in my with my public IP.**

**Comment by titulebolide** [comment]
That's not your public IP, that's your private one. Nonetheless, you can still run a reverse proxy on your machine.

**Comment by borhanreo** [comment]
When i run and open. **http://localhost:5000/** or **http://127.0.0.1:5000/** it's working. when i try to open with my local computer ip **http://192.168.0.105:5000/** then it did not work.

**Comment by borhanreo** [comment]
Thanks @titulebolide  Yes.. Now it's working

**Comment by titulebolide** [comment]
Otherwise you can try to change this:

https://github.com/ShizukuIchi/pdf-editor/blob/f3aea5c9799650def6a03fdc588e6261537f988b/rollup.config.js#L57

Into `http://0.0.0.0:5000` but I would not recommend that.

**Comment by borhanreo** [comment]
I just user reverse proxy
