### ISSUE TITLE
How to build this editor?

### ISSUE THREAD

**Issue by sunxvogy** [ShizukuIchi/pdf-editor#7]
This editor is awsome! I have tried to run the index.html in the browser directly but it seems cannot work. May I know how to build it from the source?

**Comment by FraGoTe** [comment]
@sunxvogy  first you have to install rollup

`npm i rollup`

and then

`npm start`

**Comment by sunxvogy** [comment]
Done! Thanks a lot!

**Comment by titulebolide** [comment]
Or more classically : 
```bash
yarn install #install dependencies
yarn build #build the project
yarn start #starts the server
```
